# Regularization ( Lasso and Ridge regressions)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Advertising.csv")

In [3]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [4]:
X = df.drop("sales",axis = 1)

In [5]:
y = df['sales']

In [6]:
X

TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [7]:
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64

In [8]:
from sklearn.preprocessing import PolynomialFeatures


In [9]:
polynomial_converter = PolynomialFeatures(degree=3,include_bias=True)

In [10]:
poly_features = polynomial_converter.fit_transform(X)

In [12]:
poly_features.shape

(200, 20)

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [15]:
X_train.shape

(140, 20)

In [16]:
from sklearn.preprocessing import StandardScaler

In [19]:
scaler = StandardScaler()

In [20]:
scaler.fit(X_train)

StandardScaler()

In [21]:
X_train = scaler.transform(X_train)

In [22]:
X_test = scaler.transform(X_test)

In [23]:
X_train[0]

array([ 0.        ,  0.49300171, -0.33994238,  1.61586707,  0.28407363,
       -0.02568776,  1.49677566, -0.59023161,  0.41659155,  1.6137853 ,
        0.08057172, -0.05392229,  1.01524393, -0.36986163,  0.52457967,
        1.48737034, -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [24]:
poly_features

array([[1.00000000e+00, 2.30100000e+02, 3.78000000e+01, ...,
        9.88757280e+04, 1.81010592e+05, 3.31373888e+05],
       [1.00000000e+00, 4.45000000e+01, 3.93000000e+01, ...,
        6.96564990e+04, 7.99365930e+04, 9.17338510e+04],
       [1.00000000e+00, 1.72000000e+01, 4.59000000e+01, ...,
        1.46001933e+05, 2.20434291e+05, 3.32812557e+05],
       ...,
       [1.00000000e+00, 1.77000000e+02, 9.30000000e+00, ...,
        5.53536000e+02, 3.80928000e+02, 2.62144000e+02],
       [1.00000000e+00, 2.83600000e+02, 4.20000000e+01, ...,
        1.16776800e+05, 1.84062480e+05, 2.90117528e+05],
       [1.00000000e+00, 2.32100000e+02, 8.60000000e+00, ...,
        6.43452000e+02, 6.50934000e+02, 6.58503000e+02]])

In [31]:
from sklearn.linear_model import Ridge

In [32]:
ridge_model = Ridge(alpha = 10)

In [33]:
ridge_model.fit(X_train , y_train)

Ridge(alpha=10)

In [35]:
test_predictions = ridge_model.predict(X_test)

In [36]:
from sklearn.metrics import mean_squared_error , mean_absolute_error

In [37]:
MAE = mean_absolute_error(y_test , test_predictions)

In [38]:
MAE

0.5774404204714177

In [41]:
RMSE = np.sqrt(mean_squared_error(y_test , test_predictions))

In [42]:
RMSE

0.8946386461319675

In [43]:
from sklearn.linear_model import RidgeCV

In [54]:
ridge_cv_model = RidgeCV(alphas=(0.1,1.0,10),scoring='neg_mean_absolute_error')

In [55]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(alphas=(0.1, 1.0, 10), scoring='neg_mean_absolute_error')

In [56]:
ridge_cv_model.alpha_

0.1

In [57]:
from sklearn.metrics import get_scorer_names

scorers_list = get_scorer_names()
print(scorers_list)


['accuracy', 'adjusted_mutual_info_score', 'adjusted_rand_score', 'average_precision', 'balanced_accuracy', 'completeness_score', 'explained_variance', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'fowlkes_mallows_score', 'homogeneity_score', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted', 'matthews_corrcoef', 'max_error', 'mutual_info_score', 'neg_brier_score', 'neg_log_loss', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_gamma_deviance', 'neg_mean_poisson_deviance', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_median_absolute_error', 'neg_negative_likelihood_ratio', 'neg_root_mean_squared_error', 'normalized_mutual_info_score', 'positive_likelihood_ratio', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'r2', 'rand_score', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'roc_auc', 'roc_auc_ovo', 'roc_auc_ovo_weight

In [58]:
test_predictions = ridge_cv_model.predict(X_test)

In [59]:
MAE = mean_absolute_error(y_test , test_predictions)

In [60]:
MAE

0.42737748843192336

In [61]:
RMSE = np.sqrt(mean_squared_error(y_test , test_predictions))

In [62]:
RMSE

0.6180719926946617

In [64]:
ridge_cv_model.coef_

array([ 0.        ,  5.40769392,  0.5885865 ,  0.40390395, -6.18263924,
        4.59607939, -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,
        2.5569777 , -1.38900471,  0.86059434,  0.72219553, -0.26129256,
        0.17870787,  0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [65]:
ridge_cv_model.best_score_

-0.3749223340292962

-------------------------------------------------------------------------------------------------------------------

# Lasso - least absolute shrinkage and selection operator


-------------------------------------------------------------------------------------------------------------------

In [68]:
from sklearn.linear_model import LassoCV

In [82]:
lasso_cv_model = LassoCV(eps = 0.001, n_alphas=100,cv = 5,max_iter=1000000)

In [83]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, max_iter=1000000)

In [84]:
lasso_cv_model.alpha_

0.004943070909225827

In [85]:
test_predictions = lasso_cv_model.predict(X_test)

In [86]:
MAE = mean_absolute_error(y_test , test_predictions)

In [87]:
MAE

0.4335034618590066

In [88]:
RMSE = np.sqrt(mean_squared_error(y_test , test_predictions))

In [89]:
RMSE

0.6063140748984026

In [90]:
lasso_cv_model.coef_

array([ 0.        ,  4.86023329,  0.12544598,  0.20746872, -4.99250395,
        4.38026519, -0.22977201, -0.        ,  0.07267717, -0.        ,
        1.77780246, -0.69614918, -0.        ,  0.12044132, -0.        ,
       -0.        , -0.        ,  0.        ,  0.        , -0.        ])

## Elastic NET ( L1 + L2  regression)

In [94]:
from sklearn.linear_model import ElasticNetCV

In [95]:
elastic_cv_model = ElasticNetCV(l1_ratio=[.1,.5,.7,.9,.95,.99,1],eps = 0.001 , n_alphas=100, max_iter=1000000)


In [96]:
elastic_cv_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [98]:
elastic_cv_model.l1_ratio_ ## best one

1.0

In [99]:
elastic_cv_model.alpha_

0.004943070909225827

In [100]:
test_predictions = elastic_cv_model.predict(X_test)

In [101]:
MAE = mean_absolute_error(y_test , test_predictions)

In [102]:
MAE

0.4335034618590066

In [103]:
RMSE = np.sqrt(mean_squared_error(y_test , test_predictions))

In [104]:
RMSE

0.6063140748984026